export interface AlimentoSazonal {
  id: string
  nome: string
  icone: string // Nome do ícone do Iconify
  categoria: "fruta" | "verdura" | "legume"
  meses: number[] // Array com os meses (1-12) em que o alimento está na época
  slug: string
}

export const ALIMENTOS_SAZONAIS: AlimentoSazonal[] = [
  // FRUTAS
  {
    id: "abacaxi",
    nome: "Abacaxi",
    icone: "noto:pineapple",
    categoria: "fruta",
    meses: [1, 3, 9, 10, 11, 12],
    slug: "abacaxi",
  },
  {
    id: "abacate",
    nome: "Abacate",
    icone: "noto:avocado",
    categoria: "fruta",
    meses: [2, 3, 4, 5],
    slug: "abacate",
  },
  {
    id: "acerola",
    nome: "Acerola",
    icone: "noto:cherries",
    categoria: "fruta",
    meses: [9, 10, 11, 12],
    slug: "acerola",
  },
  {
    id: "ameixa",
    nome: "Ameixa",
    icone: "noto:plum",
    categoria: "fruta",
    meses: [2, 3, 4, 12],
    slug: "ameixa",
  },
  {
    id: "amora",
    nome: "Amora",
    icone: "material-symbols:nutrition",
    categoria: "fruta",
    meses: [10, 11],
    slug: "amora",
  },
  {
    id: "banana",
    nome: "Banana",
    icone: "noto:banana",
    categoria: "fruta",
    meses: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    slug: "banana",
  },
  {
    id: "caju",
    nome: "Caju",
    icone: "material-symbols:nutrition",
    categoria: "fruta",
    meses: [6, 8, 9],
    slug: "caju",
  },
  {
    id: "caqui",
    nome: "Caqui",
    icone: "noto:tangerine",
    categoria: "fruta",
    meses: [4, 5],
    slug: "caqui",
  },
  {
    id: "carambola",
    nome: "Carambola",
    icone: "material-symbols:star",
    categoria: "fruta",
    meses: [1, 2, 6, 7, 8],
    slug: "carambola",
  },
  {
    id: "cidra",
    nome: "Cidra",
    icone: "noto:lemon",
    categoria: "fruta",
    meses: [4],
    slug: "cidra",
  },
  {
    id: "coco",
    nome: "Coco",
    icone: "noto:coconut",
    categoria: "fruta",
    meses: [1, 2, 3, 9, 10, 11, 12],
    slug: "coco",
  },
  {
    id: "cupuacu",
    nome: "Cupuaçu",
    icone: "material-symbols:nutrition",
    categoria: "fruta",
    meses: [11, 12],
    slug: "cupuacu",
  },
  {
    id: "figo",
    nome: "Figo",
    icone: "material-symbols:nutrition",
    categoria: "fruta",
    meses: [1, 2, 3, 12],
    slug: "figo",
  },
  {
    id: "fruta-do-conde",
    nome: "Fruta do Conde",
    icone: "material-symbols:nutrition",
    categoria: "fruta",
    meses: [1, 2, 3],
    slug: "fruta-do-conde",
  },
  {
    id: "goiaba",
    nome: "Goiaba",
    icone: "material-symbols:nutrition",
    categoria: "fruta",
    meses: [2, 3],
    slug: "goiaba",
  },
  {
    id: "jaca",
    nome: "Jaca",
    icone: "material-symbols:nutrition",
    categoria: "fruta",
    meses: [2, 3, 4, 5, 11, 12],
    slug: "jaca",
  },
  {
    id: "jabuticaba",
    nome: "Jabuticaba",
    icone: "noto:grapes",
    categoria: "fruta",
    meses: [9, 10, 11],
    slug: "jabuticaba",
  },
  {
    id: "kiwi",
    nome: "Kiwi",
    icone: "noto:kiwi-fruit",
    categoria: "fruta",
    meses: [4, 5, 6, 7, 8],
    slug: "kiwi",
  },
  {
    id: "laranja",
    nome: "Laranja",
    icone: "noto:tangerine",
    categoria: "fruta",
    meses: [1, 6, 8, 9, 10, 11, 12],
    slug: "laranja",
  },
  {
    id: "lima",
    nome: "Lima",
    icone: "noto:lemon",
    categoria: "fruta",
    meses: [6, 8, 9],
    slug: "lima",
  },
  {
    id: "limao",
    nome: "Limão",
    icone: "noto:lemon",
    categoria: "fruta",
    meses: [3],
    slug: "limao",
  },
  {
    id: "lichia",
    nome: "Lichia",
    icone: "material-symbols:nutrition",
    categoria: "fruta",
    meses: [12],
    slug: "lichia",
  },
  {
    id: "maca",
    nome: "Maçã",
    icone: "noto:red-apple",
    categoria: "fruta",
    meses: [2, 3, 4, 5, 6, 7, 8, 9],
    slug: "maca",
  },
  {
    id: "mamao",
    nome: "Mamão",
    icone: "material-symbols:nutrition",
    categoria: "fruta",
    meses: [1, 3, 6, 8, 9, 10, 11, 12],
    slug: "mamao",
  },
  {
    id: "manga",
    nome: "Manga",
    icone: "noto:mango",
    categoria: "fruta",
    meses: [9, 10, 11, 12],
    slug: "manga",
  },
  {
    id: "maracuja",
    nome: "Maracujá",
    icone: "material-symbols:nutrition",
    categoria: "fruta",
    meses: [1, 11, 12],
    slug: "maracuja",
  },
  {
    id: "melancia",
    nome: "Melancia",
    icone: "noto:watermelon",
    categoria: "fruta",
    meses: [1, 10, 11, 12],
    slug: "melancia",
  },
  {
    id: "melao",
    nome: "Melão",
    icone: "noto:melon",
    categoria: "fruta",
    meses: [10, 11, 12],
    slug: "melao",
  },
  {
    id: "mexerica",
    nome: "Mexerica",
    icone: "noto:tangerine",
    categoria: "fruta",
    meses: [6, 7, 8],
    slug: "mexerica",
  },
  {
    id: "morango",
    nome: "Morango",
    icone: "noto:strawberry",
    categoria: "fruta",
    meses: [6, 8],
    slug: "morango",
  },
  {
    id: "nectarina",
    nome: "Nectarina",
    icone: "noto:peach",
    categoria: "fruta",
    meses: [1, 3],
    slug: "nectarina",
  },
  {
    id: "nespera",
    nome: "Nêspera",
    icone: "material-symbols:nutrition",
    categoria: "fruta",
    meses: [9],
    slug: "nespera",
  },
  {
    id: "pera",
    nome: "Pera",
    icone: "noto:pear",
    categoria: "fruta",
    meses: [2, 3, 4, 5],
    slug: "pera",
  },
  {
    id: "pessego",
    nome: "Pêssego",
    icone: "noto:peach",
    categoria: "fruta",
    meses: [2, 3, 10, 11, 12],
    slug: "pessego",
  },
  {
    id: "pitanga",
    nome: "Pitanga",
    icone: "noto:cherries",
    categoria: "fruta",
    meses: [10, 11, 12],
    slug: "pitanga",
  },
  {
    id: "seriguela",
    nome: "Seriguela",
    icone: "noto:plum",
    categoria: "fruta",
    meses: [2, 3],
    slug: "seriguela",
  },
  {
    id: "tangerina",
    nome: "Tangerina",
    icone: "noto:tangerine",
    categoria: "fruta",
    meses: [3, 4, 5, 6, 7, 8, 9],
    slug: "tangerina",
  },
  {
    id: "uva",
    nome: "Uva",
    icone: "noto:grapes",
    categoria: "fruta",
    meses: [1, 2, 3, 4, 5, 7],
    slug: "uva",
  },

  // VERDURAS
  {
    id: "acelga",
    nome: "Acelga",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [3, 11, 12],
    slug: "acelga",
  },
  {
    id: "agrao",
    nome: "Agrião",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [6, 7, 8],
    slug: "agrao",
  },
  {
    id: "alface",
    nome: "Alface",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [1, 3, 4, 11, 12],
    slug: "alface",
  },
  {
    id: "alho-poro",
    nome: "Alho-poró",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [3, 4, 5, 6, 7, 8, 9, 10],
    slug: "alho-poro",
  },
  {
    id: "almeirao",
    nome: "Almeirão",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [4, 5, 9, 10, 11, 12],
    slug: "almeirao",
  },
  {
    id: "brocolis",
    nome: "Brócolis",
    icone: "noto:broccoli",
    categoria: "verdura",
    meses: [6, 8, 9, 10],
    slug: "brocolis",
  },
  {
    id: "catalonha",
    nome: "Catalonha",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [4, 9, 10],
    slug: "catalonha",
  },
  {
    id: "cebolinha",
    nome: "Cebolinha",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [1, 9, 11, 12],
    slug: "cebolinha",
  },
  {
    id: "chicoria",
    nome: "Chicória",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [6, 7, 8, 9, 10],
    slug: "chicoria",
  },
  {
    id: "coentro",
    nome: "Coentro",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [3, 6, 7, 8, 9, 10, 11, 12],
    slug: "coentro",
  },
  {
    id: "couve",
    nome: "Couve",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [1, 6, 7, 9, 10, 11, 12],
    slug: "couve",
  },
  {
    id: "couve-flor",
    nome: "Couve-flor",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [6, 8, 9, 10],
    slug: "couve-flor",
  },
  {
    id: "endivia",
    nome: "Endívia",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [3],
    slug: "endivia",
  },
  {
    id: "erva-doce",
    nome: "Erva-doce",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [5, 6, 7, 8, 9],
    slug: "erva-doce",
  },
  {
    id: "escarola",
    nome: "Escarola",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [2, 3, 4, 6, 8],
    slug: "escarola",
  },
  {
    id: "espinafre",
    nome: "Espinafre",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [6, 7, 8, 9, 10, 11, 12],
    slug: "espinafre",
  },
  {
    id: "folha-de-uva",
    nome: "Folha de Uva",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [9],
    slug: "folha-de-uva",
  },
  {
    id: "hortela",
    nome: "Hortelã",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [2, 9, 10],
    slug: "hortela",
  },
  {
    id: "louro",
    nome: "Louro",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [5],
    slug: "louro",
  },
  {
    id: "mostarda",
    nome: "Mostarda",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [6, 7, 8, 9, 10],
    slug: "mostarda",
  },
  {
    id: "oregano",
    nome: "Orégano",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [9],
    slug: "oregano",
  },
  {
    id: "repolho",
    nome: "Repolho",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [2, 3, 4],
    slug: "repolho",
  },
  {
    id: "rucula",
    nome: "Rúcula",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [3, 6, 8, 10, 11, 12],
    slug: "rucula",
  },
  {
    id: "salsao",
    nome: "Salsão",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [7],
    slug: "salsao",
  },
  {
    id: "salsa",
    nome: "Salsa",
    icone: "material-symbols:eco",
    categoria: "verdura",
    meses: [1, 3, 11, 12],
    slug: "salsa",
  },

  // LEGUMES
  {
    id: "abobora",
    nome: "Abóbora",
    icone: "noto:pumpkin",
    categoria: "legume",
    meses: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    slug: "abobora",
  },
  {
    id: "abobrinha",
    nome: "Abobrinha",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12],
    slug: "abobrinha",
  },
  {
    id: "alcachofra",
    nome: "Alcachofra",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [9],
    slug: "alcachofra",
  },
  {
    id: "aspargos",
    nome: "Aspargos",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [9],
    slug: "aspargos",
  },
  {
    id: "batata-doce",
    nome: "Batata-doce",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [5, 7, 9],
    slug: "batata-doce",
  },
  {
    id: "berinjela",
    nome: "Berinjela",
    icone: "noto:eggplant",
    categoria: "legume",
    meses: [2, 3, 4, 5, 9, 10, 11, 12],
    slug: "berinjela",
  },
  {
    id: "beterraba",
    nome: "Beterraba",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [1, 2, 3, 4, 5, 9, 10, 11, 12],
    slug: "beterraba",
  },
  {
    id: "cara",
    nome: "Cará",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [2, 3, 4, 5, 6, 8],
    slug: "cara",
  },
  {
    id: "cenoura",
    nome: "Cenoura",
    icone: "noto:carrot",
    categoria: "legume",
    meses: [5, 6, 7, 8, 9, 10, 11, 12],
    slug: "cenoura",
  },
  {
    id: "chuchu",
    nome: "Chuchu",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [2, 3, 4, 5, 10, 11, 12],
    slug: "chuchu",
  },
  {
    id: "cogumelo",
    nome: "Cogumelo",
    icone: "noto:mushroom",
    categoria: "legume",
    meses: [9],
    slug: "cogumelo",
  },
  {
    id: "ervilha",
    nome: "Ervilha",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [6, 8, 9],
    slug: "ervilha",
  },
  {
    id: "fava",
    nome: "Fava",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [6, 8, 9],
    slug: "fava",
  },
  {
    id: "gengibre",
    nome: "Gengibre",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [2, 3, 4, 5],
    slug: "gengibre",
  },
  {
    id: "inhame",
    nome: "Inhame",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    slug: "inhame",
  },
  {
    id: "jilo",
    nome: "Jiló",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [3],
    slug: "jilo",
  },
  {
    id: "mandioca",
    nome: "Mandioca",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [5, 6, 7, 10, 11, 12],
    slug: "mandioca",
  },
  {
    id: "mandioquinha",
    nome: "Mandioquinha",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [5, 6, 7, 8, 10, 11, 12],
    slug: "mandioquinha",
  },
  {
    id: "milho-verde",
    nome: "Milho-verde",
    icone: "noto:ear-of-corn",
    categoria: "legume",
    meses: [2, 3, 7],
    slug: "milho-verde",
  },
  {
    id: "nabo",
    nome: "Nabo",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [3, 4, 5, 6, 7, 8],
    slug: "nabo",
  },
  {
    id: "palmito",
    nome: "Palmito",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [7],
    slug: "palmito",
  },
  {
    id: "pepino",
    nome: "Pepino",
    icone: "noto:cucumber",
    categoria: "legume",
    meses: [1, 2, 3, 4, 7, 9, 10, 11, 12],
    slug: "pepino",
  },
  {
    id: "pimentao",
    nome: "Pimentão",
    icone: "noto:bell-pepper",
    categoria: "legume",
    meses: [1, 2, 6, 8, 9, 10, 11, 12],
    slug: "pimentao",
  },
  {
    id: "quiabo",
    nome: "Quiabo",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [1, 2, 3, 10, 11, 12],
    slug: "quiabo",
  },
  {
    id: "rabanete",
    nome: "Rabanete",
    icone: "material-symbols:nutrition",
    categoria: "legume",
    meses: [5, 6, 7, 8, 9, 10, 11, 12],
    slug: "rabanete",
  },
  {
    id: "tomate",
    nome: "Tomate",
    icone: "noto:tomato",
    categoria: "legume",
    meses: [1, 2, 3, 4, 9, 10, 11, 12],
    slug: "tomate",
  },
  {
    id: "tomate-caqui",
    nome: "Tomate-caqui",
    icone: "noto:tomato",
    categoria: "legume",
    meses: [9],
    slug: "tomate-caqui",
  },
]

// Função para filtrar por categoria
export function getAlimentosPorCategoria(categoria: "fruta" | "verdura" | "legume"): AlimentoSazonal[] {
  return ALIMENTOS_SAZONAIS.filter((alimento) => alimento.categoria === categoria)
}

// Função para filtrar por mês e categoria
export function getAlimentosPorMesECategoria(
  mes: number,
  categoria?: "fruta" | "verdura" | "legume",
): AlimentoSazonal[] {
  let alimentos = ALIMENTOS_SAZONAIS.filter((alimento) => alimento.meses.includes(mes))

  if (categoria) {
    alimentos = alimentos.filter((alimento) => alimento.categoria === categoria)
  }

  return alimentos
}
